// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package plandb

import (
	"time"
)

type ExecutionMetric struct {
	ID               int64
	AgentName        string
	Model            string
	PromptTokens     int64
	CompletionTokens int64
	LatencyMs        int64
	Timestamp        time.Time
}

type Recipe struct {
	ID        string
	Data      string
	UpdatedAt time.Time
}

type RecipeEmbedding struct {
	RecipeID  string
	Embedding []byte
	TextHash  string
}

type ShoppingList struct {
	ID         int64
	UserID     string
	MealPlanID int64
	Items      string
	CreatedAt  time.Time
}

type UserMealPlan struct {
	ID            int64
	UserID        string
	PlanData      string
	WeekStartDate time.Time
	Status        string
	CreatedAt     time.Time
}
