// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_queries.sql

package auditdb

import (
	"context"
	"database/sql"
	"time"
)

const cleanupAuditLogs = `-- name: CleanupAuditLogs :exec
DELETE FROM audit_logs WHERE created_at < ?
`

func (q *Queries) CleanupAuditLogs(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, cleanupAuditLogs, createdAt)
	return err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (
    user_id, plan_id, action_type, original_request, user_feedback, previous_state, new_state
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditLogParams struct {
	UserID          string
	PlanID          sql.NullInt64
	ActionType      string
	OriginalRequest sql.NullString
	UserFeedback    sql.NullString
	PreviousState   sql.NullString
	NewState        sql.NullString
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.UserID,
		arg.PlanID,
		arg.ActionType,
		arg.OriginalRequest,
		arg.UserFeedback,
		arg.PreviousState,
		arg.NewState,
	)
	return err
}
