// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shopping_queries.sql

package shoppingdb

import (
	"context"
	"time"
)

const deleteShoppingListByMealPlanID = `-- name: DeleteShoppingListByMealPlanID :exec
DELETE FROM shopping_lists
WHERE meal_plan_id = ?
`

func (q *Queries) DeleteShoppingListByMealPlanID(ctx context.Context, mealPlanID int64) error {
	_, err := q.db.ExecContext(ctx, deleteShoppingListByMealPlanID, mealPlanID)
	return err
}

const getShoppingListByMealPlanID = `-- name: GetShoppingListByMealPlanID :one
SELECT id, user_id, meal_plan_id, items, created_at FROM shopping_lists
WHERE meal_plan_id = ?
LIMIT 1
`

func (q *Queries) GetShoppingListByMealPlanID(ctx context.Context, mealPlanID int64) (ShoppingList, error) {
	row := q.db.QueryRowContext(ctx, getShoppingListByMealPlanID, mealPlanID)
	var i ShoppingList
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MealPlanID,
		&i.Items,
		&i.CreatedAt,
	)
	return i, err
}

const getShoppingListByUserAndWeek = `-- name: GetShoppingListByUserAndWeek :one
SELECT sl.id, sl.user_id, sl.meal_plan_id, sl.items, sl.created_at
FROM shopping_lists sl
INNER JOIN user_meal_plans ump ON sl.meal_plan_id = ump.id
WHERE sl.user_id = ? AND ump.week_start_date = ?
LIMIT 1
`

type GetShoppingListByUserAndWeekParams struct {
	UserID        string
	WeekStartDate time.Time
}

func (q *Queries) GetShoppingListByUserAndWeek(ctx context.Context, arg GetShoppingListByUserAndWeekParams) (ShoppingList, error) {
	row := q.db.QueryRowContext(ctx, getShoppingListByUserAndWeek, arg.UserID, arg.WeekStartDate)
	var i ShoppingList
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MealPlanID,
		&i.Items,
		&i.CreatedAt,
	)
	return i, err
}

const insertShoppingList = `-- name: InsertShoppingList :one
INSERT INTO shopping_lists (user_id, meal_plan_id, items, created_at)
VALUES (?, ?, ?, ?)
RETURNING id
`

type InsertShoppingListParams struct {
	UserID     string
	MealPlanID int64
	Items      string
	CreatedAt  time.Time
}

func (q *Queries) InsertShoppingList(ctx context.Context, arg InsertShoppingListParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertShoppingList,
		arg.UserID,
		arg.MealPlanID,
		arg.Items,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
