// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_queries.sql

package sessiondb

import (
	"context"
	"time"
)

const cleanupExpiredSessions = `-- name: CleanupExpiredSessions :exec
DELETE FROM user_sessions WHERE expires_at <= ?
`

func (q *Queries) CleanupExpiredSessions(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredSessions, expiresAt)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO user_sessions (user_id, session_type, state, context_data, expires_at, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateSessionParams struct {
	UserID      string
	SessionType string
	State       string
	ContextData string
	ExpiresAt   time.Time
	CreatedAt   time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.UserID,
		arg.SessionType,
		arg.State,
		arg.ContextData,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM user_sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT id, user_id, session_type, state, context_data, expires_at, created_at
FROM user_sessions
WHERE user_id = ? AND expires_at > ?
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveSessionParams struct {
	UserID    string
	ExpiresAt time.Time
}

func (q *Queries) GetActiveSession(ctx context.Context, arg GetActiveSessionParams) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, getActiveSession, arg.UserID, arg.ExpiresAt)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionType,
		&i.State,
		&i.ContextData,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE user_sessions
SET state = ?, context_data = ?
WHERE id = ?
`

type UpdateSessionParams struct {
	State       string
	ContextData string
	ID          int64
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateSession, arg.State, arg.ContextData, arg.ID)
	return err
}
