// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipe_queries.sql

package recipedb

import (
	"context"
	"strings"
	"time"
)

const deleteRecipeByID = `-- name: DeleteRecipeByID :exec
DELETE FROM recipes WHERE id = ?
`

func (q *Queries) DeleteRecipeByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRecipeByID, id)
	return err
}

const deleteRecipeTags = `-- name: DeleteRecipeTags :exec
DELETE FROM recipe_tags
WHERE recipe_id = ?
`

func (q *Queries) DeleteRecipeTags(ctx context.Context, recipeID string) error {
	_, err := q.db.ExecContext(ctx, deleteRecipeTags, recipeID)
	return err
}

const getRandomRecipes = `-- name: GetRandomRecipes :many
SELECT id, data, updated_at FROM recipes
WHERE id NOT IN (/*SLICE:exclude_ids*/?)
ORDER BY RANDOM()
LIMIT ?
`

type GetRandomRecipesParams struct {
	ExcludeIds []string
	Limit      int64
}

func (q *Queries) GetRandomRecipes(ctx context.Context, arg GetRandomRecipesParams) ([]Recipe, error) {
	query := getRandomRecipes
	var queryParams []interface{}
	if len(arg.ExcludeIds) > 0 {
		for _, v := range arg.ExcludeIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:exclude_ids*/?", strings.Repeat(",?", len(arg.ExcludeIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:exclude_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(&i.ID, &i.Data, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipeByID = `-- name: GetRecipeByID :one
SELECT id, data, updated_at FROM recipes
WHERE id = ?
`

func (q *Queries) GetRecipeByID(ctx context.Context, id string) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipeByID, id)
	var i Recipe
	err := row.Scan(&i.ID, &i.Data, &i.UpdatedAt)
	return i, err
}

const getRecipeIDsByTags = `-- name: GetRecipeIDsByTags :many
SELECT DISTINCT recipe_id
FROM recipe_tags
WHERE tag IN (/*SLICE:tags*/?)
`

func (q *Queries) GetRecipeIDsByTags(ctx context.Context, tags []string) ([]string, error) {
	query := getRecipeIDsByTags
	var queryParams []interface{}
	if len(tags) > 0 {
		for _, v := range tags {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tags*/?", strings.Repeat(",?", len(tags))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tags*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var recipe_id string
		if err := rows.Scan(&recipe_id); err != nil {
			return nil, err
		}
		items = append(items, recipe_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipesByIDs = `-- name: GetRecipesByIDs :many
SELECT id, data, updated_at FROM recipes
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) GetRecipesByIDs(ctx context.Context, ids []string) ([]Recipe, error) {
	query := getRecipesByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(&i.ID, &i.Data, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRecipe = `-- name: InsertRecipe :exec
INSERT INTO recipes (id, data, updated_at)
VALUES (?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    data = EXCLUDED.data,
    updated_at = EXCLUDED.updated_at
WHERE EXCLUDED.updated_at > recipes.updated_at
`

type InsertRecipeParams struct {
	ID        string
	Data      string
	UpdatedAt time.Time
}

func (q *Queries) InsertRecipe(ctx context.Context, arg InsertRecipeParams) error {
	_, err := q.db.ExecContext(ctx, insertRecipe, arg.ID, arg.Data, arg.UpdatedAt)
	return err
}

const insertRecipeTag = `-- name: InsertRecipeTag :exec
INSERT INTO recipe_tags (recipe_id, tag)
VALUES (?, ?)
ON CONFLICT (recipe_id, tag) DO NOTHING
`

type InsertRecipeTagParams struct {
	RecipeID string
	Tag      string
}

func (q *Queries) InsertRecipeTag(ctx context.Context, arg InsertRecipeTagParams) error {
	_, err := q.db.ExecContext(ctx, insertRecipeTag, arg.RecipeID, arg.Tag)
	return err
}

const listAllRecipes = `-- name: ListAllRecipes :many
SELECT id, data, updated_at FROM recipes
ORDER BY updated_at DESC
`

func (q *Queries) ListAllRecipes(ctx context.Context) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listAllRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(&i.ID, &i.Data, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipes = `-- name: ListRecipes :many
SELECT id, data, updated_at FROM recipes
WHERE id NOT IN (/*SLICE:exclude_ids*/?)
ORDER BY updated_at DESC
`

func (q *Queries) ListRecipes(ctx context.Context, excludeIds []string) ([]Recipe, error) {
	query := listRecipes
	var queryParams []interface{}
	if len(excludeIds) > 0 {
		for _, v := range excludeIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:exclude_ids*/?", strings.Repeat(",?", len(excludeIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:exclude_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(&i.ID, &i.Data, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipeData = `-- name: UpdateRecipeData :exec
UPDATE recipes
SET data = ?
WHERE id = ?
`

type UpdateRecipeDataParams struct {
	Data string
	ID   string
}

func (q *Queries) UpdateRecipeData(ctx context.Context, arg UpdateRecipeDataParams) error {
	_, err := q.db.ExecContext(ctx, updateRecipeData, arg.Data, arg.ID)
	return err
}
