// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recipe_queries.sql

package recipedb

import (
	"context"
	"strings"
	"time"
)

const countRecipes = `-- name: CountRecipes :one
SELECT COUNT(id) FROM recipes
`

func (q *Queries) CountRecipes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecipes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRecipeByID = `-- name: DeleteRecipeByID :exec
DELETE FROM recipes WHERE id = ?
`

func (q *Queries) DeleteRecipeByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRecipeByID, id)
	return err
}

const getRecipeByID = `-- name: GetRecipeByID :one
SELECT id, data, updated_at FROM recipes
WHERE id = ?
`

func (q *Queries) GetRecipeByID(ctx context.Context, id string) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipeByID, id)
	var i Recipe
	err := row.Scan(&i.ID, &i.Data, &i.UpdatedAt)
	return i, err
}

const getRecipesByIDs = `-- name: GetRecipesByIDs :many
SELECT id, data, updated_at FROM recipes
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) GetRecipesByIDs(ctx context.Context, ids []string) ([]Recipe, error) {
	query := getRecipesByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(&i.ID, &i.Data, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRecipe = `-- name: InsertRecipe :exec
INSERT INTO recipes (id, data, updated_at)
VALUES (?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    data = EXCLUDED.data,
    updated_at = EXCLUDED.updated_at
WHERE EXCLUDED.updated_at > recipes.updated_at
`

type InsertRecipeParams struct {
	ID        string
	Data      string
	UpdatedAt time.Time
}

func (q *Queries) InsertRecipe(ctx context.Context, arg InsertRecipeParams) error {
	_, err := q.db.ExecContext(ctx, insertRecipe, arg.ID, arg.Data, arg.UpdatedAt)
	return err
}

const listAllRecipes = `-- name: ListAllRecipes :many
SELECT id, data, updated_at FROM recipes
ORDER BY updated_at DESC
`

func (q *Queries) ListAllRecipes(ctx context.Context) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listAllRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(&i.ID, &i.Data, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipes = `-- name: ListRecipes :many
SELECT id, data, updated_at FROM recipes
WHERE id NOT IN (/*SLICE:exclude_ids*/?)
ORDER BY updated_at DESC
`

func (q *Queries) ListRecipes(ctx context.Context, excludeIds []string) ([]Recipe, error) {
	query := listRecipes
	var queryParams []interface{}
	if len(excludeIds) > 0 {
		for _, v := range excludeIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:exclude_ids*/?", strings.Repeat(",?", len(excludeIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:exclude_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(&i.ID, &i.Data, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
